
namespace Kamilla.Network.Protocols.Wow.Latest.Game
{
    public enum CurrencyTypes
    {
        CurrencyTokenTestToken4 = 1,
        CurrencyTokenTestToken2 = 2,
        CurrencyTokenTestToken5 = 4,
        BadgeofJustice = 42,
        DalaranJewelcraftersToken = 61,
        DalaranCookingAward = 81,
        ChampionsSeal = 241,
        ChefsAward = 402,
        ArenaPoints = 103,
        HonorPointsDEPRECATED = 104,
        AlteracValleyMarkofHonor = 121,
        ArathiBasinMarkofHonor = 122,
        EyeoftheStormMarkofHonor = 123,
        StrandoftheAncientsMarkofHonor = 124,
        WarsongGulchMarkofHonor = 125,
        WintergraspMarkofHonor = 126,
        StoneKeepersShard = 161,
        HonorPointsDEPRECATED2 = 181,
        VentureCoin = 201,
        IsleofConquestMarkofHonor = 321,
        ConquestPoints = 390,
        TolBaradCommendation = 391,
        HonorPoints = 392,
        EmblemofHeroism = 101,
        EmblemofValor = 102,
        EmblemofConquest = 221,
        EmblemofTriumph = 301,
        EmblemofFrost = 341,
        JusticePoints = 395,
        ValorPoints = 396,
        BirminghamTestItem3 = 22,
        IllustriousJewelcraftersToken = 361,
        DwarfArchaeologyFragment = 384,
        TrollArchaeologyFragment = 385,
        FossilArchaeologyFragment = 393,
        NightElfArchaeologyFragment = 394,
        OrcArchaeologyFragment = 397,
        DraeneiArchaeologyFragment = 398,
        VrykulArchaeologyFragment = 399,
        NerubianArchaeologyFragment = 400,
        TolvirArchaeologyFragment = 401,
        zzzOLDDailyQuestFactionToken = 141,
        MarkOfTheWorldTree = 416,
        ConquestArenaMeta = 483,
        ConquestBattlegroundMeta = 484,
    }
}
