using System;

namespace Kamilla.Network.Protocols.Wow.Latest.Game
{
    public enum ChatMessageType : uint
    {
        Addon                      = uint.MaxValue,
        Addon2                     = byte.MaxValue,
        System                     = 0x00,
        Say                        = 0x01,
        Party                      = 0x02,
        Raid                       = 0x03,
        Guild                      = 0x04,
        Officer                    = 0x05,
        Yell                       = 0x06,
        Whisper                    = 0x07,
        WhisperForeign             = 0x08,
        WhisperInform              = 0x09,
        Emote                      = 0x0A,
        TextEmote                  = 0x0B,
        MonsterSay                 = 0x0C,
        MonsterParty               = 0x0D,
        MonsterYell                = 0x0E,
        MonsterWhisper             = 0x0F,
        MonsterEmote               = 0x10,
        Channel                    = 0x11,
        ChannelJoin                = 0x12,
        ChannelLeave               = 0x13,
        ChannelList                = 0x14,
        ChannelNotice              = 0x15,
        ChannelNoticeUser          = 0x16,
        AFK                        = 0x17,
        DND                        = 0x18,
        Ignored                    = 0x19,
        Skill                      = 0x1A,
        Loot                       = 0x1B,
        Money                      = 0x1C,
        Opening                    = 0x1D,
        Tradeskills                = 0x1E,
        PetInfo                    = 0x1F,
        CombatMiscInfo             = 0x20,
        CombatXPGain               = 0x21,
        CombatHonorGain            = 0x22,
        CombatFactionChange        = 0x23,
        BGSystemNeutral            = 0x24,
        BGSystemAlliance           = 0x25,
        BGSystemHorde              = 0x26,
        RaidLeader                 = 0x27,
        RaidWarning                = 0x28,
        RaidBossEmote              = 0x29,
        RaidBossWhisper            = 0x2A,
        Filtered                   = 0x2B,
        Battleground               = 0x2C,
        BattlegroundLeader         = 0x2D,
        Restricted                 = 0x2E,
        BattleNet                  = 0x2F,
        Achievement                = 0x30,
        GuildAchievement           = 0x31,
        ArenaPoints                = 0x32,
        PartyGuide                 = 0x33
    };

    public enum Language : uint
    {
        Universal       = 0,
        Orcish          = 1,
        Darnassian      = 2,
        Taurahe         = 3,
        Dwarvish        = 6,
        Common          = 7,
        Demonic         = 8,
        Titan           = 9,
        Thalassian      = 10,
        Draconic        = 11,
        Kalimag         = 12,
        Gnomish         = 13,
        Troll           = 14,
        Gutterspeak     = 33,
        Draenei         = 35,
        Zombie          = 36,
        GnomishBinary   = 37,
        GoblinBinary    = 38,
        Addon           = uint.MaxValue
    }

    [Flags]
    public enum SocialFlag
    {
        Friend          = 0x01,
        Ignored         = 0x02,
        Muted           = 0x04,  // guessed
        RecruitAFriend  = 0x08,  // Recruit-A-Friend
    }

    public enum FriendStatus
    {
        Offline = 0,
        Online  = 1,
        AFK     = 2,
        Unk3    = 3,
        DND     = 4,
    }

    public enum ChatMessageFlags : byte
    {
        None        = 0x00,

        Tag_AFK     = 0x01,
        Tag_DND     = 0x02,
        Tag_GM      = 0x04,
        Unk_0x08    = 0x08,
        Tag_DEV     = 0x10,
        PlaySound   = 0x20,
        Unk_0x40    = 0x40,
        Tag_COM     = 0x80,
    }

    public enum ChannelNotification : byte
    {
        PlayerJoined                = 0x00,
        PlayerLeft                  = 0x01,
        YouJoined                   = 0x02,
        YouLeft                     = 0x03,
        WrongPassword               = 0x04,
        NotOnChannel                = 0x05,
        NotModerator                = 0x06,
        PasswordChanged             = 0x07,
        OwnerChanged                = 0x08,
        PlayerNotOnChannel          = 0x09,
        NotOwner                    = 0x0A,
        CurrentOwner                = 0x0B,
        Mute                        = 0x0C,
        Moderator                   = 0x0C,
        Announcing                  = 0x0D,
        NotAnnouncing               = 0x0E,
        Moderated                   = 0x0F,
        NotModerated                = 0x10,
        YouAreMuted                 = 0x11,
        Kicked                      = 0x12,
        YouAreBanned                = 0x13,
        Banned                      = 0x14,
        Unbanned                    = 0x15,
        PlayerNotBanned             = 0x16,
        AlreadyOnChannel            = 0x17,
        BeenInvitedToChannel        = 0x18,
        InviteWrongFaction          = 0x19,
        WrongAlliance               = 0x1A,
        InvalidChannelName          = 0x1B,
        ChannelIsNotModerated       = 0x1C,
        HaveInvitedToChannel        = 0x1D,
        CannotInviteBannedPlayer    = 0x1E,
        ChatThrottledNotice         = 0x1F,
        NotInCorrectAreaForChannel  = 0x20,
        NotInLFGQueue               = 0x21,
        VoiceEnabled                = 0x22,
        VoiceDisabled               = 0x23,
        VoiceEnabled2               = 0x24,
    }

    public enum ChatRestrictionType
    {
        ChatRestricted  = 0,
        ChatThrottled   = 1,
        UserSquelched   = 2,
        YellRestricted  = 3
    }

    public enum TextEmote
    {
        Agree        = 1,
        Amaze        = 2,
        Angry        = 3,
        Apologize    = 4,
        Applaud      = 5,
        Bashful      = 6,
        Beckon       = 7,
        Beg          = 8,
        Bite         = 9,
        Bleed        = 10,
        Blink        = 11,
        Blush        = 12,
        Bonk         = 13,
        Bored        = 14,
        Bounce       = 15,
        Brb          = 16,
        Bow          = 17,
        Burp         = 18,
        Bye          = 19,
        Cackle       = 20,
        Cheer        = 21,
        Chicken      = 22,
        Chuckle      = 23,
        Clap         = 24,
        Confused     = 25,
        Congratulate = 26,
        Cough        = 27,
        Cower        = 28,
        Crack        = 29,
        Cringe       = 30,
        Cry          = 31,
        Curious      = 32,
        Curtsey      = 33,
        Dance        = 34,
        Drink        = 35,
        Drool        = 36,
        Eat          = 37,
        Eye          = 38,
        Fart         = 39,
        Fidget       = 40,
        Flex         = 41,
        Frown        = 42,
        Gasp         = 43,
        Gaze         = 44,
        Giggle       = 45,
        Glare        = 46,
        Gloat        = 47,
        Greet        = 48,
        Grin         = 49,
        Groan        = 50,
        Grovel       = 51,
        Guffaw       = 52,
        Hail         = 53,
        Happy        = 54,
        Hello        = 55,
        Hug          = 56,
        Hungry       = 57,
        Kiss         = 58,
        Kneel        = 59,
        Laugh        = 60,
        Laydown      = 61,
        Massage      = 62,
        Moan         = 63,
        Moon         = 64,
        Mourn        = 65,
        No           = 66,
        Nod          = 67,
        Nosepick     = 68,
        Panic        = 69,
        Peer         = 70,
        Plead        = 71,
        Point        = 72,
        Poke         = 73,
        Pray         = 74,
        Roar         = 75,
        Rofl         = 76,
        Rude         = 77,
        Salute       = 78,
        Scratch      = 79,
        Sexy         = 80,
        Shake        = 81,
        Shout        = 82,
        Shrug        = 83,
        Shy          = 84,
        Sigh         = 85,
        Sit          = 86,
        Sleep        = 87,
        Snarl        = 88,
        Spit         = 89,
        Stare        = 90,
        Surprised    = 91,
        Surrender    = 92,
        Talk         = 93,
        Talkex       = 94,
        Talkq        = 95,
        Tap          = 96,
        Thank        = 97,
        Threaten     = 98,
        Tired        = 99,
        Victory      = 100,
        Wave         = 101,
        Welcome      = 102,
        Whine        = 103,
        Whistle      = 104,
        Work         = 105,
        Yawn         = 106,
        Boggle       = 107,
        Calm         = 108,
        Cold         = 109,
        Comfort      = 110,
        Cuddle       = 111,
        Duck         = 112,
        Insult       = 113,
        Introduce    = 114,
        Jk           = 115,
        Lick         = 116,
        Listen       = 117,
        Lost         = 118,
        Mock         = 119,
        Ponder       = 120,
        Pounce       = 121,
        Praise       = 122,
        Purr         = 123,
        Puzzle       = 124,
        Raise        = 125,
        Ready        = 126,
        Shimmy       = 127,
        Shiver       = 128,
        Shoo         = 129,
        Slap         = 130,
        Smirk        = 131,
        Sniff        = 132,
        Snub         = 133,
        Soothe       = 134,
        Stink        = 135,
        Taunt        = 136,
        Tease        = 137,
        Thirsty      = 138,
        Veto         = 139,
        Snicker      = 140,
        Stand        = 141,
        Tickle       = 142,
        Violin       = 143,
        Smile        = 163,
        Rasp         = 183,
        Pity         = 203,
        Growl        = 204,
        Bark         = 205,
        Scared       = 223,
        Flop         = 224,
        Love         = 225,
        Moo          = 226,
        Commend      = 243,
        Joke         = 329,
        Wink         = 363,
        Pat          = 364,
        Serious      = 365,
        MountSpecial = 366,
        Goodluck     = 367,
        Blame        = 368,
        Blank        = 369,
        Brandish     = 370,
        Breath       = 371,
        Disagree     = 372,
        Doubt        = 373,
        Embarras     = 374,
        Encourage    = 375,
        Enemy        = 376,
        Eyebrow      = 377,
        Toast        = 378,
    }
}
